jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 150
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - script: |
      mvn -v
      mvn clean install
    displayName: 'Build Ballerina'
